[package]
name = "amazing-wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
phf = { version = "0.12.1", features = ["macros"] }
#amazing-crypto = { path = "../amazing-crypto" }