[workspace]
members = [
    "amazing-crypto",
    "amazing-crypto/core",
    "amazing-wasm",
    "amazing-egui",
]
resolver = "3"

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
